#!/usr/bin/env bash
#
# bootstrap installs things. Stolen from Holmans and then adapted

DOTFILES_ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  if [ ! -z "$SPIN" ]
  then
    # Remove Spin's defaults
    rm -f $HOME/{.profile,.zshrc,.gitconfig}
  fi

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  if [ "$(uname -s)" == "Darwin" ]
  then
    mkdir -p "$HOME/.gnupg"
    link_file "$DOTFILES_ROOT/gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"
    link_file "$DOTFILES_ROOT/gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"
  fi

  mkdir -p "$HOME/.config"
  link_file "$DOTFILES_ROOT/nvim" "$HOME/.config/nvim"
}

install_dotfiles

# On macOS: Homebrew + apps + macOS defaults
if [ "$(uname -s)" == "Darwin" ]
then
  info "setting up macOS + apps"
  if source macos/install.sh | while read -r data; do info "$data"; done
  then
    success "macOS + apps done"
  else
    fail "error setting up macOS + apps"
  fi
fi

# Pure:
git submodule update --init --recursive
git pull --recurse-submodules --ff-only

info "installing vim plugins"
# Why does this core dump?
# nvim -E +PlugInstall +qall
nvim --headless +PlugInstall +qall

echo ''
echo '  All installed!'
