brew "rg"
brew "tldr"
brew "neovim"
brew "htop"
brew "git"
brew "fzf"
brew "gnupg"
brew "pinentry-mac"
brew "bat"
brew "htop"
brew "node"

cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "1password"
cask "keepingyouawake"
cask "fork"
cask "tableplus"
cask "vlc"
cask "spotify"
cask "visual-studio-code"

# Shopify only
if ENV["SHOPIFY"]
  cask "tuple"
  brew "mycli"
end
